config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root "home#index"

  get 'contact', to: "home#contact"

  delete 'signout', to: "sessions#destroy"

  get "signup", to: "users#new"

  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"
  get "auth", to: "users#auth", as: "auth"
  resources :users, :categories, :search, :gifts, :requests, :swaps
get "accept_request", to: "requests#accept"

  resources :gifts do
    resources :requests
  end

  resources :conversations do
    resources :messages
  end
  post 'gifts/accept/:id', to: 'gifts#accept', as: 'accept'
  get 'gifts/accept/:id', to: 'gifts#accept'
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :gifts
  has_many :requests, through: :gifts
  has_many :swaps
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :username, uniqueness: true, length: { minimum: 5 }
  validates :password, length: { minimum: 10 }
  validates_presence_of :name, :email, :username

  def self.authenticate!(username, password)
    user = find_by(username: username)
    user.authenticate(password) if user
  end

  def get_user_gifts
    @user_gifts = Gift.where(user_id: self.id)
    @gifts =  @user_gifts.select do |gift|
      if Swap.find_by(item_id: gift.id) == nil
        gift
      end
    end
    @gifts
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @errors = @user.errors
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thank you for signing up to Regifter, #{@user.username}!"
    else
      @errors = @user.errors
      render 'new'
    end
  end

  def edit
    set_user
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thank you for updating your profile, #{@user.username}!"
    else
      @errors = @user.errors
      render 'edit'
    end
  end

  def update
    set_user
    @user.update(user_params)
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
    @gifts = @user.get_user_gifts
    @completed_swaps = Swap.where("new_owner_id = ?", @user.id)
  end

  def destroy
    set_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :address, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<%= form_for @user, class: 'form-horizontal' do |f| %>
  <div class = "col-sm-12">
    <div class="form-group required">
      <%= f.label "Name", class: "col-sm-2 control-label" %>
      <%= f.text_field :name, class: "form-control", placeholder: "John Smith" %>
      <% if @errors.full_messages_for(:name) != [] %>
        <% @errors.full_messages_for(:name).each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      <% end %>
    </div>
    <br>
    <div class="form-group required">
      <%= f.label "Email:", class: "col-sm-2 control-label" %>
      <%= f.email_field :email, placeholder: 'name@example.com', class: "form-control" %>
      <% if @errors.full_messages_for(:email) != [] %>
        <% @errors.full_messages_for(:email).each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      <% end %>
    </div>
    <br>
    <div class="form-group required">
      <%= f.label "Username", class: "col-sm-2 control-label" %>
      <%= f.text_field :username, class: "form-control", placeholder: "jsmith123" %>
      <% if @errors.full_messages_for(:username) != [] %>
        <% @errors.full_messages_for(:username).each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      <% end %>
    </div>
    <br>
    <div class="form-group required">
      <%= f.label "Address", class: "col-sm-2 control-label" %>
      <%= f.text_area :address, class: "form-control" %>
      <% if @errors.full_messages_for(:address) != [] %>
        <% @errors.full_messages_for(:address).each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      <% end %>
    </div>
    <br>
    <div class="form-group required">
      <%= f.label "Password", class: "col-sm-2 control-label" %>
      <%= f.password_field :password, help: "Must be at least 10 characters long", class: "form-control" %>
      <% if @errors.full_messages_for(:password) != [] %>
        <% @errors.full_messages_for(:password).each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      <% end %>
    </div>
    <br>
    <div class="form-group required">
      <%= f.label "Confirm Password", class: "col-sm-2 control-label" %>
      <%= f.password_field :password_confirmation, class: "form-control"  %>
      <% if @errors.full_messages_for(:password_confirmation) != [] %>
        <% @errors.full_messages_for(:password_confirmation).each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      <% end %>
    </div><br>
    <div class="actions">
      <%= f.submit class: "btn btn-primary"%>
    </div><br>
  </div>
<% end %>

app/views/users/_my_gifts.html.erb
<h4>Your unwanted gifts:</h4>
<div class="grid">
<% @gifts.each do |gift| %>

    <div id=<%=gift.id%> class="product-grid col-xs-6 col-md-4 grid-item panel panel-default">
        <div class="product-thumb" data-sr >
          <figure >
            <!-- <div class="panel-heading">
              <h3 class="panel-title"><%= link_to gift.title.capitalize %></h3>
            </div> -->
            <!-- <div class="panel-body"> -->

          <div class="image">
                      <%= image_tag gift.image, class: "img-responsive" %>
            </div>
                  <figcaption>
                    <div class="name">
                      <%= link_to  gift.title, gift_path(gift) %>
                    </div>
                    <div class="price">
                      $<%= gift.value %>
                    </div>
                  </figcaption>
            </figure>
          </div>
<!-- </div> -->
            <%@swaps={}%>

            <%@unwanted_gift = nil%>
            <%@wanted_gift = nil%>

            <%gift.requests_wanted.map do |x| %>
              <%@swaps[x.unwanted_gift.user.username]= x.unwanted_gift.title %>
              <%@unwanted_gift= x.unwanted_gift%>
              <%@wanted_gift = x.wanted_gift%>
            <%end%>

                <% if logged_in? && params[:id].to_i == current_user.id%>

                  
                        <div style="margin-bottom: 200px;">
                          <%= link_to 'Edit', edit_gift_path(gift), class: "col-xs-12 btn btn-default" %>

                        <%= button_to "Delete", {  remote: true, controller: :gifts, action: "destroy", id: gift.id }, method: :delete,
                        class: "col-xs-12 btn btn-default", data: { confirm: "Are you sure?" } %>

                        <% if logged_in? && params[:id].to_i == current_user.id%>
                            <%@swaps.each do |person, gift|%>
                            <%= form_tag(accept_path(@unwanted_gift)) do |f| %>
                              <%=hidden_field_tag :wanted_id, @wanted_gift.id%>
                              <%=submit_tag 'Pending!', class: "col-xs-12 btn btn-primary" %>
                            <%end%>
                        <%end%>

                  <%end%>

                <% end %>
</div>

        </div>

<% end %>
</div>
<div class="clearfix"></div>

app/views/users/_swaps.html.erb
<div class="col-xs-12">
<h4>Your Completed Swaps </h4>
  <% @completed_swaps.each do |swap| %>
    <% @gift = Gift.find(swap.item_id) %>
    <% @swapped_gift = Gift.find(swap.swapped_item_id) %>
    <% @old_owner = User.find(swap.old_owner_id) %>
    <% @new_owner = User.find(swap.new_owner_id) %>

      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <td class="text-left">Gift</td>
              <td class="text-left">Description</td>
              <td class="text-left">Brand</td>
              <td class="text-left">Value</td>
              <td class="text-right">Previous Owner</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="text-left">
                <p><%=@gift.title%></p>
              </td>
              <td class="text-left">
                <p><%=@gift.description%></p>
              </td>
              <td class="text-left">
                <p><%=@gift.brand%></p>
              </td>
              <td class="text-left">
                <p><%=@gift.value%></p>
              </td>
              <td class="text-right">
                <% if @old_owner == current_user %>
                <p>You</p>
                <% else %>
                <p><%=@old_owner.username %></p>
                <% end %>
              </td>
            </tr>
            <tr>
              <td class="text-left">
                <p><%=@swapped_gift.title%></p>
              </td>
              <td class="text-left">
                <p><%=@swapped_gift.description%></p>
              </td>
              <td class="text-left">
                <p><%=@swapped_gift.brand%></p>
              </td>
              <td class="text-left">
                <p><%=@swapped_gift.value%></p>
              </td>
              <td class="text-right">
                <% if @new_owner == current_user %>
                <p>You</p>
                <% else %>

                <p><%=@new_owner.username %></p>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

  <% end %>
</div>

app/views/users/auth.html.erb
<% if flash[:auth] %>
<%= flash[:auth] %>
<% end %>
<br>
<h3>Please <%= link_to "sign in", signin_path %> or <%= link_to "sign up", signup_path %>.</h3>

app/views/users/edit.html.erb
<div class="container">
<div class="col-xs-12">
<h1>Edit Your Profile</h1>
</div>
<%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class="container">
<div class="col-xs-12">

<ul class="breadcrumb">
  <li><%= link_to "", gifts_path, class:"icon ion-ios-home-outline" %></li>
  <li><%= link_to "Sign Up", signup_path %></li>
</ul>

<h1>Create Your Profile</h1>
</div>
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <ul class="breadcrumb">
    <li><%= link_to "", gifts_path, class:"icon ion-ios-home-outline" %></li>
    <li><%= link_to "Profile", user_path(@user) %></li>
  </ul>

<h2>Your Profile</h2>
<br>
    <h4><strong>USER: </strong><%= @user.name %></h4>

<% if logged_in? && params[:id].to_i == current_user.id%>
  <p><strong>Email: </strong>
    <%= @user.email %></p><br>
  <p><strong>Address: </strong>
    <%= @user.address %></p><br>
    <div id="footershow">
        <%= link_to 'Edit User', edit_user_path, class: "btn btn-default" %>
        <%= link_to 'Delete Profile', @user, method: :delete, class: "btn btn-default", data: { confirm: 'Are you sure?' } %>
        <%= link_to "Add a Gift", "/gifts/new", class: "btn btn-default" %>
        <hr>
    </div>
          <% if @gifts == [] %>
            <h4>Looks like you have no gifts listed.</h4>
          <% else %>
            <%= render "my_gifts" %>
          <% end %>

<% end %>

    <% if @completed_swaps != [] %>
      <%= render "swaps" %>
    <% end %>
</div>

app/views/users/update.html.erb
<p><%=@user.name%></p>