config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root "home#index"

  get 'contact', to: "home#contact"

  delete 'signout', to: "sessions#destroy"

  get "signup", to: "users#new"

  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"
  get "auth", to: "users#auth", as: "auth"
  resources :users, :categories, :search, :gifts, :requests, :swaps
get "accept_request", to: "requests#accept"

  resources :gifts do
    resources :requests
  end

  resources :conversations do
    resources :messages
  end
  post 'gifts/accept/:id', to: 'gifts#accept', as: 'accept'
  get 'gifts/accept/:id', to: 'gifts#accept'
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"
end

app/models/gift.rb
class Gift < ActiveRecord::Base
  belongs_to :user
  has_many :items, class_name: "Swap", foreign_key: :item_id
  has_many :swapped_items, class_name: "Swap", foreign_key: :swapped_item_id
  has_many :requests, foreign_key: :wanted_id, dependent: :destroy
  accepts_nested_attributes_for :requests
  has_many :gift_categories, dependent: :destroy
  has_many :categories, through: :gift_categories
  accepts_nested_attributes_for :categories
  accepts_nested_attributes_for :requests
  validates_presence_of :title, :value, :description, :brand, :image
  mount_uploader :image, AssetUploader
  include PgSearch
  pg_search_scope :search, against: [:title, :description, :brand]

  

  def requests_wanted
    Request.where(wanted_id: id)
  end

  def requests_made
    Request.where(unwanted_id: id)
  end

  def self.get_all_gifts
    self.joins("LEFT OUTER JOIN swaps ON gifts.id = swaps.item_id")
        .where(swaps: {item_id: nil})
  end

end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  skip_before_action(:authenticate!, except: [:new, :create])

  def index
    @categories = Category.all
    @gifts = Gift.get_all_gifts
    if params[:category].present?
      @gifts = @gifts.joins(:gift_categories).where("gift_categories.category_id" => params[:category])
    end
  end

  def new
    if !logged_in?
      flash[:auth] = "Sorry, you must be signed in to a gift."
      redirect_to auth_path
    else
      @gift = Gift.new
      @gift.categories.build
      @errors = @gift.errors
    end
  end

  def create
    @user = current_user
    @gift = @user.gifts.build(gift_params)
    if @gift.save
      @gifts = @user.get_user_gifts
      redirect_to @user,:notice => "Item added!"
    else
      @errors = @gift.errors
      render 'new'
    end
  end

  def edit
    set_gift
    @errors = @gift.errors
  end

  def update
    @user = current_user
    set_gift
    @gift.update(gift_params)
    redirect_to @user
  end

  def show
    @gift = Gift.find(params[:id])
  end

  def accept
    
    @wanted_id = params[:wanted_id]
    @gift = Gift.find(params[:id])
    @accept = true
    render 'show'
  end

  def destroy
    set_gift
    @deleted_id = @gift.id

    @gift.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
      format.js {}
    end
  end

  private

  def set_gift
    @gift = Gift.find(params[:id])
  end

  def gift_params
    params.require(:gift).permit(:title, :value, :description, :brand, :image, :user_id, categories_attributes: [:title], category_ids: [], request_ids: [])
  end
end

app/views/gifts/_form.html.erb
<div>
<%= form_for @gift, class: 'form-horizontal' do |f| %>
    <div class="form-group">
      <%= f.label "Title:", class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :title, class: "form-control" %>
        <% if @errors.full_messages_for(:title) %>
          <p><%= @errors.full_messages_for(:title)[0] %></p>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "Value:", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :value, prepend: "$", append: ".00", class: "form-control" %>
        <% if @errors.full_messages_for(:value) %>
          <p><%= @errors.full_messages_for(:value)[0] %></p>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "Description:", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control" %>
        <% if @errors.full_messages_for(:description) %>
          <p><%= @errors.full_messages_for(:description)[0] %></p>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label "Brand:", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :brand, class: "form-control" %>
        <% if @errors.full_messages_for(:brand) %>
          <p><%= @errors.full_messages_for(:brand)[0] %></p>
        <% end %>
      </div>
    </div>
  

    <div class="form-group">
      <%= f.label "Upload an Image:", class:"col-sm-2"%>

            <%= f.file_field :image, class:"col-sm-8" %>

    <% if @errors.full_messages_for(:image) %>
        <p><%= @errors.full_messages_for(:image)[0] %></p>
      <% end %>
    </div>

  </div>




  <div style= "padding: 0px" class="form-group col-sm-12">
     <%= f.label "Category:", class: "control-label col-sm-2" %>
     <div class="col-sm-5">
        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :title) do |b| %>
          <div class="col-xs-4">
            <%= b.label do %>
              <%= b.check_box + " " + b.text %>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <br><br>
    </div>
  </div>
<% end %>
</div>

app/views/gifts/destroy.js.erb
var gift = <%=@deleted_id %>

$("#" + gift).remove()

app/views/gifts/edit.html.erb
<div class="container">
<h1>Edit Your Gift</h1>

<%= render 'form' %>
<%= link_to  "gift", @gift %>
|
<%= link_to 'Back', gifts_path %>
</div>

app/views/gifts/index.html.erb
<div class="container">
  <div class="grid">
    <%@gifts.each do |gift|%>
    <div id=<%=gift.id%> class="product-grid col-xs-6 col-sm-3 grid-item">
      <div class="product-thumb" data-sr>
        <figure>
          <div class="image">
            <%= image_tag gift.image, class:"img-responsive"  %>
          </div>
          <figcaption>
            <div class="name">
              <%= link_to  gift.title, gift_path(gift) %>
            </div>
            <div class="price">
              $<%= gift.value %>
            </div>
          </figcaption>
        </figure>
      </div>
    </div>
    <%end%>
  </div>

</div>

app/views/gifts/new.html.erb
<div class="container">
  <ul class="breadcrumb">
    <li><%= link_to "", gifts_path, class:"icon ion-ios-home-outline" %></li>
    <li><%= link_to "Profile", user_path(current_user) %></li>
  </ul>

  <div class="row">
    <h1>Add A Gift</h1>
  </div>

    <%= render 'form' %>
</div>

app/views/gifts/show.html.erb
<div class="container">
  <div class="row product-page">
    <div id="content" class="col-sm-12">
      <div class="row">
        <div class="col-sm-6">
          <ul class="breadcrumb">
            <li><%= link_to "", root_path, class:"icon ion-ios-home-outline" %></li>
            <li><%= link_to "Gifts", gifts_path %></li>
            <li><a href="#"><%=@gift.title%></a></li>
          </ul>
          <br/>
          <%= image_tag @gift.image, class:"img-responsive"  %>
          <br/ >
          <% if logged_in? && current_user[:id] != @gift.user.id%>
              <%user_to_message=@gift.user.id%>
              <%sender=current_user.id%>
<!-- start convo -->
                  <%= form_tag(conversations_path) do%>
                      <%=hidden_field_tag :sender_id, sender%>
                      <%= hidden_field_tag :recipient_id, user_to_message %>
                      <%=submit_tag "Message "+@gift.user.username+" here", class: "btn btn-primary btn-block"%>
                  <%end%>
<!-- accept swap -->
<%unwanted_id=params[:wanted_id]%>
<%wanted_id=@gift.id%>
              <% if @accept %>
                  <%= link_to 'Accept Swap!', accept_request_path(request:{unwanted_id: unwanted_id, wanted_id: wanted_id}), class: "btn btn-primary btn-block" %>
              <%else%>
                  <%= link_to 'Propose Swap!', new_gift_request_path(@gift), class: "btn btn-primary btn-block" %>
              <%end%>
        </p>
        <% elsif logged_in? %>
        <p class="accent"> This item belongs to you </p>
        <% else %>
        <p class="accent"> <%= link_to "Sign in", signin_path %> or <%= link_to "sign up", signup_path %> to propose a swap or message a user </p>
        <% end %>
        </div>

        <div class="col-sm-6">
          <h1><%=@gift.title%></h1>
          <div class="table-responsive">
            <table class="table">
              <tr>
                <td>Brand:</td>
                <td> <%= @gift.brand %></td>
              </tr>
              <tr>
                <td>Value:</td>
                <td>$<%= @gift.value %></td>
              </tr>
              <tr>
                <td>Categories:</td>
                <td><%= @gift.categories.pluck(:title).join(", ")%></td>
              </tr>
            </table>
          </div>
          <hr>
          <!-- Description -->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title"><a href="#collapse-description" data-toggle="collapse" data-parent="#accordion" class="accordion-toggle">Description <i class="fa fa-angle-down"></i></a></h4>
            </div>
            <div id="collapse-description" class="panel-collapse collapse">
              <div class="panel-body">
                <p><%=@gift.description%></p>
              </div>
            </div>
          </div>
          <!--/ Description -->
          <br />
        </div>
      </div>
    </div>
  </div>
</div>