config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root "home#index"

  get 'contact', to: "home#contact"

  delete 'signout', to: "sessions#destroy"

  get "signup", to: "users#new"

  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"
  get "auth", to: "users#auth", as: "auth"
  resources :users, :categories, :search, :gifts, :requests, :swaps
get "accept_request", to: "requests#accept"

  resources :gifts do
    resources :requests
  end

  resources :conversations do
    resources :messages
  end
  post 'gifts/accept/:id', to: 'gifts#accept', as: 'accept'
  get 'gifts/accept/:id', to: 'gifts#accept'
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"
end

app/views/layouts/_header.html.erb
<% if flash[:error] %>
<%= flash[:error] %>
<% end %>

<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<div id="nav">
  <%= link_to "HOME", gifts_path %>
  <% if logged_in? %>
  You are logged in,
  <%= current_user.name %>
  <%= link_to "Sign Out", signout_path, method: :delete %>
  <%= link_to "Messages", conversations_path %>
  <%= link_to "Add a Gift", new_gift_path %>
  <%= link_to "Profile", user_path(current_user) %>
  <% else %>
  <%= link_to "Sign In", signin_path %>
  <%= link_to "Sign Up", signup_path %>
  <%end%>
</div><br><br><br>

<div>
  <%= form_tag("/search", method: "get") do %>
  <%= label_tag(:query, "Search for regifts:") %>
  <%= text_field_tag :query, params[:query], placeholder: "I want to find..."%>
  <%= submit_tag("Search") %>
  <% end %>
</div><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

       <title>Regifter</title>


   <link href="//fonts.googleapis.com/css?family=Roboto:400,300,500,700" rel="stylesheet">

   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>



  </head>
  <body>
  <% if flash[:error] %>
    <%= flash[:error] %>
  <% end %>


  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>

    <nav class="side-nav side-nav-left">
      <h2><%= link_to "SWAPR", root_path %></h2>
      <ul class="list-unstyled">
        <li><%= link_to "All Gifts", gifts_path %></li>
        <% Category.all.each do |category| %>
          <li><%= link_to category.title, gifts_path(category: category.id)%></li>
        <% end %>
      </ul>
    </nav>
    <div class="site-overlay"></div>
    <div class="wrapper">

      <header>
        <div class="container-fluid">

          <div class="row">
            <div class="col-sm-12">
              <div class="menu pull-left" data-toggle="tooltip" data-placement="bottom" title="Menu"><i class="icon ion-ios-more"></i></div>
              <div class="account pull-right">
                <ul class="list-inline">
                  <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle"><i class="icon ion-ios-person-outline" data-toggle="tooltip" data-placement="bottom" title="My Account"></i></a>
                    <ul class="dropdown-menu dropdown-menu-right text-center">
                      <li class="dropdown-triangle"></li>
                        <% if logged_in? %>
                          <li><%= link_to "Profile", user_path(current_user) %></li>
                          <li><%= link_to "Add a Gift", new_gift_path %></li>
                          <li><%= link_to "Messages", conversations_path %></li>
                          <li><%= link_to "Sign Out", signout_path, method: :delete %></li>
                        <% else %>
                          <li><%= link_to "Visitor Sign In", signin_path%></li>
                          <li><%= link_to "Sign In", signin_path %></li>
                          <li><%= link_to "Sign Up", signup_path %></li>
                        <%end%>
                    </ul>
                  </li>
                </ul>
              </div>

              <div class="search pull-right">
                <div class="btn-group">
      <form action="/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
                  <a href="/search" data-toggle="dropdown" class="dropdown-toggle"><i class="icon ion-ios-search-strong" data-toggle="tooltip" data-placement="bottom" data-container="body" title="Search"></i></a>
                  <ul class="dropdown-menu pull-right">
                      <li class="dropdown-triangle"></li>
                      <li>
                        <div class="input-group">
                            <input type="text" name="query" id="query" placeholder="I want to find..." class="form-control">
                          <div class="input-group-btn">
                            <input type="submit" name="commit" value="Search" class="btn btn-default">
                          </div>
                        </div>
                      </li>
                    </ul>
          </form>
</div>


                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
      </header>

<!-- Where slideshow used to be -->

     <%= yield %>


      <footer>
<div class="container-fluid">
          <div class="row">

            <div class="col-sm-4">
              <div class="btn-group dropup info">
                <button type="button" class="dropdown-toggle">
                  <i class="icon ion-ios-information-outline"></i>
                  <span><%= link_to 'Contact Us', contact_path, {style: "color:white"}  %></span>
                </button>
              </div>
            </div>

            <div class="col-sm-4">
              <div class="btn-group dropup user-account" style="padding-bottom: 45px;">
                  <i class="icon ion-ios-person-outline"></i>
                  <% if logged_in? %>
                  <span><%= link_to 'My Account', user_path(current_user), {style: "color:white"}  %></span>
                  <% else %>
                  <span><%= link_to 'Login', signin_path, {style: "color:white"}  %></span>
                  <% end %>
              </div>
            </div>

            <div class="col-sm-4">
              <div class="btn-group dropup powered">
                <button type="button" data-toggle="dropdown" class="dropdown-toggle">
                  <i class="icon ion-ios-bolt-outline"></i>
                  <span>Designed with love by:</span>
                </button>
                <ul class="dropdown-menu pull-right">
                  <li class="dropdown-triangle"></li>
                  <li><a href="https://github.com/LindaHaviv">Linda</a></li>
                  <li><a href="https://github.com/jscheuc1">Johnny</a></li>
                  <li><a href="https://github.com/leighsn">Leigh</a></li>
                  <li><a href="https://github.com/nat-ser">Nataliya</a></li>
                </ul>
              </div>
            </div>

          </div>
  </div>
      </footer>

  </div>


    <!-- <span id="home"></span> -->

   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <script>
    $(document).ready(function() {
      // Main banners slideshow

      $("#slideshow").owlCarousel({
        items: 6,
        autoPlay: 6000,
        singleItem: true,
        navigation: true,
        responsive: true,
        navigationText: ['<i class="fa fa-angle-left"></i>', '<i class="fa fa-angle-right"></i>'],
        pagination: true
      });

      // scrollReveal plugin
      window.sr = new scrollReveal();
    });
    $(window).load(function(){
      $('.grid').masonry({
        // options
      itemSelector: '.grid-item',
      columnWidth: 200
      });
    });

    </script>
  </body>
</html>